name: bloom

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - {ubuntu: resolute, ros: lyrical}

    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ matrix.ubuntu }}
          ROS_DISTRO: ${{ matrix.ros }}
